version: '3'

services:
  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - .:/app
      - ./.docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    container_name: php
    build: .docker/php
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mariadb
    container_name: bd
    environment:
      MYSQL_DATABASE: ideasdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./.docker/db/data:/var/lib/mysql
      - ./.docker/dump:/.docker-entrypoint-initdb.d
